import * as mgmtApi from "@agility/management-sdk";
import _ from "lodash";
import { ReferenceMapper } from "../reference-mapper";
import { logModelDifferences } from "../loggers";

/**
 * Model Comparison Utilities - Extracted from model-pusher.ts
 * Provides model difference detection logic for sync operations
 */

// Helper function to compare two models, ignoring ID and field order
export function areModelsDifferent(
  sourceModel: mgmtApi.Model,
  targetModel: mgmtApi.Model,
  shouldLogDiffs: boolean,
  referenceMapper: ReferenceMapper
): boolean {
  // Create copies to avoid modifying originals
  const sourceCopy = _.cloneDeep(sourceModel);
  const targetCopy = _.cloneDeep(targetModel);

  // Ignore IDs and other purely informational fields that shouldn't trigger a diff if they are the only difference
  delete sourceCopy.id;
  delete targetCopy.id;
  delete sourceCopy.lastModifiedDate;
  delete targetCopy.lastModifiedDate;
  delete sourceCopy.lastModifiedAuthorID;
  delete targetCopy.lastModifiedAuthorID;
  delete sourceCopy.lastModifiedBy;
  delete targetCopy.lastModifiedBy;
  delete sourceCopy.allowTagging;
  delete targetCopy.allowTagging;
  // CRITICAL FIX: Ignore wasUnpublished as it's not relevant for sync operations
  delete (sourceCopy as any).wasUnpublished;
  delete (targetCopy as any).wasUnpublished;
  delete sourceCopy.contentDefinitionTypeName;
  delete targetCopy.contentDefinitionTypeName;
  // CRITICAL FIX: Ignore contentDefinitionTypeID differences due to API bug
  // The Management API doesn't properly update contentDefinitionTypeID in model updates
  delete (sourceCopy as any).contentDefinitionTypeID;
  delete (targetCopy as any).contentDefinitionTypeID;
  delete sourceCopy.displayName;
  delete targetCopy.displayName;

  // CRITICAL: Ignore bridge fields added by ChainDataLoader for compatibility
  delete (sourceCopy as any).definitionID;
  delete (targetCopy as any).definitionID;
  delete (sourceCopy as any).definitionName;
  delete (targetCopy as any).definitionName;

  // CRITICAL: Ignore fields that may be undefined in source but missing in target
  delete (sourceCopy as any).isModuleList;
  delete (targetCopy as any).isModuleList;
  delete (sourceCopy as any).sortOrder;
  delete (targetCopy as any).sortOrder;
  delete (sourceCopy as any).description;
  delete (targetCopy as any).description;

  sourceCopy.referenceName = sourceCopy.referenceName.toLowerCase();
  targetCopy.referenceName = targetCopy.referenceName.toLowerCase();

  // CRITICAL FIX: Handle missing fields property (modules have no fields property)
  // Ensure both models have fields arrays for processing
  if (!sourceCopy.fields) sourceCopy.fields = [];
  if (!targetCopy.fields) targetCopy.fields = [];

  // Sort fields by name for consistent comparison
  sourceCopy.fields.sort((a, b) => (a.name || "").localeCompare(b.name || ""));
  targetCopy.fields.sort((a, b) => (a.name || "").localeCompare(b.name || ""));

  // Normalize field settings for comparison only - be more conservative about what we filter
  const normalizeFieldSettings = (fields: mgmtApi.ModelField[], referenceMapper: ReferenceMapper) => {
    fields.forEach((field) => {
      if (field.settings) {
        // CRITICAL FIX: Skip ContentDefinition differences during comparison
        // The API handles reference resolution automatically, so these differences are irrelevant
        // Source uses reference names, target uses IDs - both are valid, API converts as needed
        if (field.type === "Content" && field.settings.ContentDefinition) {
          // Remove ContentDefinition from comparison entirely - let API handle conversion
          delete field.settings.ContentDefinition;
        }

        // Only filter out truly empty/irrelevant values for comparison
        field.settings = Object.fromEntries(
          Object.entries(field.settings).filter(([key, value]) => {
            // Keep all non-empty values - structural differences ARE important
            if (value === "" || value === null || value === undefined) return false;
            return true;
          })
        );
      }
      // Only ignore field IDs and itemOrder for comparison (these are auto-generated by target)
      delete field.fieldID;
      delete field.itemOrder;
    });
  };

  normalizeFieldSettings(sourceCopy.fields, referenceMapper);
  normalizeFieldSettings(targetCopy.fields, referenceMapper);

  // Perform a deep comparison on the modified copies
  const areDifferent = !_.isEqual(sourceCopy, targetCopy);

  if (areDifferent && shouldLogDiffs) {
    logModelDifferences(sourceCopy, targetCopy, sourceModel.referenceName);
  }

  return areDifferent;
} 